
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Mar 17 06:55:34 CET 2025
//----------------------------------------------------

import java_cup.runtime.*;

/** CUP v0.11a beta 20060608 generated parser.
  * @version Mon Mar 17 06:55:34 CET 2025
  */
public class CoolParser extends java_cup.runtime.lr_parser {

  /** Default constructor. */
  public CoolParser() {super();}

  /** Constructor which sets the default scanner. */
  public CoolParser(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public CoolParser(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\055\000\002\002\003\000\002\002\004\000\002\003" +
    "\003\000\002\003\004\000\002\004\010\000\002\004\012" +
    "\000\002\004\005\000\002\005\002\000\002\005\003\000" +
    "\002\005\004\000\002\006\006\000\002\006\010\000\002" +
    "\006\014\000\002\013\002\000\002\013\003\000\002\013" +
    "\005\000\002\014\005\000\002\007\003\000\002\007\003" +
    "\000\002\007\003\000\002\007\003\000\002\007\005\000" +
    "\002\007\004\000\002\007\005\000\002\007\005\000\002" +
    "\007\005\000\002\007\004\000\002\007\005\000\002\007" +
    "\005\000\002\007\005\000\002\007\005\000\002\007\004" +
    "\000\002\007\004\000\002\007\005\000\002\007\007\000" +
    "\002\007\004\000\002\015\007\000\002\015\011\000\002" +
    "\015\007\000\002\015\011\000\002\012\003\000\002\012" +
    "\004\000\002\011\010\000\002\010\004\000\002\010\005" +
    "" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\154\000\004\004\007\001\002\000\006\002\001\004" +
    "\007\001\002\000\004\002\155\001\002\000\006\002\uffff" +
    "\004\uffff\001\002\000\006\003\011\055\010\001\002\000" +
    "\006\011\014\050\013\001\002\000\004\043\012\001\002" +
    "\000\006\002\ufffb\004\ufffb\001\002\000\006\051\ufffa\056" +
    "\021\001\002\000\004\055\015\001\002\000\004\050\016" +
    "\001\002\000\006\051\ufffa\056\021\001\002\000\006\051" +
    "\ufff9\056\ufff9\001\002\000\006\051\150\056\021\001\002" +
    "\000\006\044\022\045\023\001\002\000\004\055\142\001" +
    "\002\000\010\042\ufff4\046\ufff4\056\025\001\002\000\006" +
    "\042\ufff3\046\ufff3\001\002\000\004\044\140\001\002\000" +
    "\006\042\027\046\030\001\002\000\004\056\025\001\002" +
    "\000\004\044\031\001\002\000\004\055\032\001\002\000" +
    "\004\050\033\001\002\000\032\012\047\020\043\024\035" +
    "\025\041\027\044\041\046\045\050\050\034\052\037\053" +
    "\036\054\040\056\042\001\002\000\032\012\047\020\043" +
    "\024\035\025\041\027\044\041\046\045\050\050\034\052" +
    "\037\053\036\054\040\056\042\001\002\000\004\055\130" +
    "\001\002\000\034\010\uffee\022\uffee\030\uffee\032\uffee\033" +
    "\uffee\034\uffee\035\uffee\036\uffee\037\uffee\042\uffee\043\uffee" +
    "\046\uffee\051\uffee\001\002\000\034\010\uffef\022\uffef\030" +
    "\uffef\032\uffef\033\uffef\034\uffef\035\uffef\036\uffef\037\uffef" +
    "\042\uffef\043\uffef\046\uffef\051\uffef\001\002\000\034\010" +
    "\ufff0\022\ufff0\030\ufff0\032\ufff0\033\ufff0\034\ufff0\035\ufff0" +
    "\036\ufff0\037\ufff0\042\ufff0\043\ufff0\046\ufff0\051\ufff0\001" +
    "\002\000\032\012\047\020\043\024\035\025\041\027\044" +
    "\041\046\045\050\050\034\052\037\053\036\054\040\056" +
    "\042\001\002\000\034\010\uffed\022\uffed\030\uffed\032\uffed" +
    "\033\uffed\034\uffed\035\uffed\036\uffed\037\uffed\042\uffed\043" +
    "\uffed\046\uffed\051\uffed\001\002\000\032\012\047\020\043" +
    "\024\035\025\041\027\044\041\046\045\050\050\034\052" +
    "\037\053\036\054\040\056\042\001\002\000\032\012\047" +
    "\020\043\024\035\025\041\027\044\041\046\045\050\050" +
    "\034\052\037\053\036\054\040\056\042\001\002\000\022" +
    "\030\057\032\056\033\061\034\060\035\054\036\053\037" +
    "\052\051\110\001\002\000\032\012\047\020\043\024\035" +
    "\025\041\027\044\041\046\045\050\050\034\052\037\053" +
    "\036\054\040\056\042\001\002\000\004\056\072\001\002" +
    "\000\032\012\047\020\043\024\035\025\041\027\044\041" +
    "\046\045\050\050\034\052\037\053\036\054\040\056\042" +
    "\001\002\000\022\030\057\032\056\033\061\034\060\035" +
    "\054\036\053\037\052\046\055\001\002\000\032\012\047" +
    "\020\043\024\035\025\041\027\044\041\046\045\050\050" +
    "\034\052\037\053\036\054\040\056\042\001\002\000\032" +
    "\012\047\020\043\024\035\025\041\027\044\041\046\045" +
    "\050\050\034\052\037\053\036\054\040\056\042\001\002" +
    "\000\032\012\047\020\043\024\035\025\041\027\044\041" +
    "\046\045\050\050\034\052\037\053\036\054\040\056\042" +
    "\001\002\000\034\010\uffec\022\uffec\030\uffec\032\uffec\033" +
    "\uffec\034\uffec\035\uffec\036\uffec\037\uffec\042\uffec\043\uffec" +
    "\046\uffec\051\uffec\001\002\000\032\012\047\020\043\024" +
    "\035\025\041\027\044\041\046\045\050\050\034\052\037" +
    "\053\036\054\040\056\042\001\002\000\032\012\047\020" +
    "\043\024\035\025\041\027\044\041\046\045\050\050\034" +
    "\052\037\053\036\054\040\056\042\001\002\000\032\012" +
    "\047\020\043\024\035\025\041\027\044\041\046\045\050" +
    "\050\034\052\037\053\036\054\040\056\042\001\002\000" +
    "\032\012\047\020\043\024\035\025\041\027\044\041\046" +
    "\045\050\050\034\052\037\053\036\054\040\056\042\001" +
    "\002\000\034\010\uffe6\022\uffe6\030\uffe6\032\uffe6\033\uffe6" +
    "\034\uffe6\035\uffe6\036\uffe6\037\uffe6\042\uffe6\043\uffe6\046" +
    "\uffe6\051\uffe6\001\002\000\034\010\uffe5\022\uffe5\030\uffe5" +
    "\032\uffe5\033\061\034\uffe5\035\054\036\uffe5\037\uffe5\042" +
    "\uffe5\043\uffe5\046\uffe5\051\uffe5\001\002\000\026\010\uffe9" +
    "\022\uffe9\032\056\033\061\034\060\035\054\042\uffe9\043" +
    "\uffe9\046\uffe9\051\uffe9\001\002\000\034\010\uffe4\022\uffe4" +
    "\030\uffe4\032\uffe4\033\061\034\uffe4\035\054\036\uffe4\037" +
    "\uffe4\042\uffe4\043\uffe4\046\uffe4\051\uffe4\001\002\000\034" +
    "\010\uffe3\022\uffe3\030\uffe3\032\uffe3\033\uffe3\034\uffe3\035" +
    "\uffe3\036\uffe3\037\uffe3\042\uffe3\043\uffe3\046\uffe3\051\uffe3" +
    "\001\002\000\026\010\uffea\022\uffea\032\056\033\061\034" +
    "\060\035\054\042\uffea\043\uffea\046\uffea\051\uffea\001\002" +
    "\000\026\010\uffe8\022\uffe8\032\056\033\061\034\060\035" +
    "\054\042\uffe8\043\uffe8\046\uffe8\051\uffe8\001\002\000\034" +
    "\010\uffde\022\uffde\030\uffde\032\uffde\033\uffde\034\uffde\035" +
    "\uffde\036\uffde\037\uffde\042\uffde\043\uffde\046\uffde\051\uffde" +
    "\001\002\000\004\044\073\001\002\000\004\055\074\001" +
    "\002\000\010\010\076\026\077\042\075\001\002\000\004" +
    "\056\072\001\002\000\032\012\047\020\043\024\035\025" +
    "\041\027\044\041\046\045\050\050\034\052\037\053\036" +
    "\054\040\056\042\001\002\000\032\012\047\020\043\024" +
    "\035\025\041\027\044\041\046\045\050\050\034\052\037" +
    "\053\036\054\040\056\042\001\002\000\024\010\101\030" +
    "\057\032\056\033\061\034\060\035\054\036\053\037\052" +
    "\042\102\001\002\000\032\012\047\020\043\024\035\025" +
    "\041\027\044\041\046\045\050\050\034\052\037\053\036" +
    "\054\040\056\042\001\002\000\004\056\072\001\002\000" +
    "\034\010\uffdc\022\uffdc\030\uffdc\032\uffdc\033\uffdc\034\uffdc" +
    "\035\uffdc\036\uffdc\037\uffdc\042\uffdc\043\uffdc\046\uffdc\051" +
    "\uffdc\001\002\000\034\010\uffda\022\uffda\030\057\032\056" +
    "\033\061\034\060\035\054\036\053\037\052\042\uffda\043" +
    "\uffda\046\uffda\051\uffda\001\002\000\034\010\uffdb\022\uffdb" +
    "\030\057\032\056\033\061\034\060\035\054\036\053\037" +
    "\052\042\uffdb\043\uffdb\046\uffdb\051\uffdb\001\002\000\034" +
    "\010\uffdd\022\uffdd\030\uffdd\032\uffdd\033\uffdd\034\uffdd\035" +
    "\uffdd\036\uffdd\037\uffdd\042\uffdd\043\uffdd\046\uffdd\051\uffdd" +
    "\001\002\000\034\010\uffe7\022\uffe7\030\uffe7\032\uffe7\033" +
    "\uffe7\034\uffe7\035\uffe7\036\uffe7\037\uffe7\042\uffe7\043\uffe7" +
    "\046\uffe7\051\uffe7\001\002\000\004\043\111\001\002\000" +
    "\006\051\ufff5\056\ufff5\001\002\000\034\010\uffeb\022\uffeb" +
    "\030\057\032\056\033\061\034\060\035\054\036\053\037" +
    "\052\042\uffeb\043\uffeb\046\uffeb\051\uffeb\001\002\000\022" +
    "\022\114\030\057\032\056\033\061\034\060\035\054\036" +
    "\053\037\052\001\002\000\004\056\116\001\002\000\006" +
    "\021\126\056\116\001\002\000\004\043\120\001\002\000" +
    "\006\021\uffd9\056\uffd9\001\002\000\004\055\121\001\002" +
    "\000\004\023\122\001\002\000\032\012\047\020\043\024" +
    "\035\025\041\027\044\041\046\045\050\050\034\052\037" +
    "\053\036\054\040\056\042\001\002\000\022\030\057\032" +
    "\056\033\061\034\060\035\054\036\053\037\052\043\124" +
    "\001\002\000\006\021\uffd7\056\uffd7\001\002\000\006\021" +
    "\uffd8\056\uffd8\001\002\000\034\010\uffdf\022\uffdf\030\uffdf" +
    "\032\uffdf\033\uffdf\034\uffdf\035\uffdf\036\uffdf\037\uffdf\042" +
    "\uffdf\043\uffdf\046\uffdf\051\uffdf\001\002\000\034\010\uffe2" +
    "\022\uffe2\030\uffe2\032\uffe2\033\uffe2\034\uffe2\035\uffe2\036" +
    "\uffe2\037\uffe2\042\uffe2\043\uffe2\046\uffe2\051\uffe2\001\002" +
    "\000\034\010\uffe1\022\uffe1\030\uffe1\032\uffe1\033\uffe1\034" +
    "\uffe1\035\uffe1\036\uffe1\037\uffe1\042\uffe1\043\uffe1\046\uffe1" +
    "\051\uffe1\001\002\000\022\030\057\032\056\033\061\034" +
    "\060\035\054\036\053\037\052\043\136\001\002\000\034" +
    "\012\047\020\043\024\035\025\041\027\044\041\046\045" +
    "\050\050\034\051\134\052\037\053\036\054\040\056\042" +
    "\001\002\000\022\030\057\032\056\033\061\034\060\035" +
    "\054\036\053\037\052\043\135\001\002\000\034\010\uffe0" +
    "\022\uffe0\030\uffe0\032\uffe0\033\uffe0\034\uffe0\035\uffe0\036" +
    "\uffe0\037\uffe0\042\uffe0\043\uffe0\046\uffe0\051\uffe0\001\002" +
    "\000\034\012\uffd5\020\uffd5\024\uffd5\025\uffd5\027\uffd5\041" +
    "\uffd5\045\uffd5\050\uffd5\051\uffd5\052\uffd5\053\uffd5\054\uffd5" +
    "\056\uffd5\001\002\000\034\012\uffd6\020\uffd6\024\uffd6\025" +
    "\uffd6\027\uffd6\041\uffd6\045\uffd6\050\uffd6\051\uffd6\052\uffd6" +
    "\053\uffd6\054\uffd6\056\uffd6\001\002\000\006\042\ufff2\046" +
    "\ufff2\001\002\000\004\055\141\001\002\000\006\042\ufff1" +
    "\046\ufff1\001\002\000\006\026\144\043\143\001\002\000" +
    "\006\051\ufff7\056\ufff7\001\002\000\032\012\047\020\043" +
    "\024\035\025\041\027\044\041\046\045\050\050\034\052" +
    "\037\053\036\054\040\056\042\001\002\000\022\030\057" +
    "\032\056\033\061\034\060\035\054\036\053\037\052\043" +
    "\146\001\002\000\006\051\ufff6\056\ufff6\001\002\000\006" +
    "\051\ufff8\056\ufff8\001\002\000\004\043\151\001\002\000" +
    "\006\002\ufffc\004\ufffc\001\002\000\006\051\153\056\021" +
    "\001\002\000\004\043\154\001\002\000\006\002\ufffd\004" +
    "\ufffd\001\002\000\004\002\000\001\002\000\006\002\ufffe" +
    "\004\ufffe\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\154\000\010\002\004\003\003\004\005\001\001\000" +
    "\004\004\155\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\006\005\151\006\016\001\001\000\002" +
    "\001\001\000\002\001\001\000\006\005\017\006\016\001" +
    "\001\000\002\001\001\000\004\006\146\001\001\000\002" +
    "\001\001\000\002\001\001\000\006\013\025\014\023\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\004\014\136\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\004\007\044\001\001\000\006" +
    "\007\130\010\131\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\004\007\126" +
    "\001\001\000\002\001\001\000\004\007\112\001\001\000" +
    "\004\007\111\001\001\000\002\001\001\000\004\007\106" +
    "\001\001\000\004\015\070\001\001\000\004\007\050\001" +
    "\001\000\002\001\001\000\004\007\067\001\001\000\004" +
    "\007\066\001\001\000\004\007\065\001\001\000\002\001" +
    "\001\000\004\007\064\001\001\000\004\007\063\001\001" +
    "\000\004\007\062\001\001\000\004\007\061\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\004\015\105\001\001\000\004\007" +
    "\104\001\001\000\004\007\077\001\001\000\002\001\001" +
    "\000\004\007\103\001\001\000\004\015\102\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\006\011\116" +
    "\012\114\001\001\000\004\011\124\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\004\007\122\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\004\007\132\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\004" +
    "\007\144\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\004" +
    "\006\146\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$CoolParser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$CoolParser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$CoolParser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 1;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}



    int omerrs = 0;

    public void syntax_error(Symbol cur_token) {
        int lineno = action_obj.curr_lineno();
	String filename = action_obj.curr_filename().getString();
        System.err.print("\"" + filename + "\", line " + lineno +
		         ": parse error at or near ");
        Utilities.printToken(cur_token);
	omerrs++;
	if (omerrs>50) {
	   System.err.println("More than 50 errors");
	   System.exit(1);
	}
    }

    public void unrecovered_syntax_error(Symbol cur_token) {
    }

}

/** Cup generated class to encapsulate user supplied action code.*/
class CUP$CoolParser$actions {



    int curr_lineno() {
	return ((CoolTokenLexer)parser.getScanner()).curr_lineno();
    }

    AbstractSymbol curr_filename() {
	return ((CoolTokenLexer)parser.getScanner()).curr_filename();
    }

  private final CoolParser parser;

  /** Constructor */
  CUP$CoolParser$actions(CoolParser parser) {
    this.parser = parser;
  }

  /** Method with the actual generated action code. */
  public final java_cup.runtime.Symbol CUP$CoolParser$do_action(
    int                        CUP$CoolParser$act_num,
    java_cup.runtime.lr_parser CUP$CoolParser$parser,
    java.util.Stack            CUP$CoolParser$stack,
    int                        CUP$CoolParser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$CoolParser$result;

      /* select the action based on the action number */
      switch (CUP$CoolParser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 44: // block_expr_list ::= block_expr_list expr SEMI 
            {
              Expressions RESULT =null;
		Expressions el = (Expressions)((java_cup.runtime.Symbol) CUP$CoolParser$stack.elementAt(CUP$CoolParser$top-2)).value;
		Expression e = (Expression)((java_cup.runtime.Symbol) CUP$CoolParser$stack.elementAt(CUP$CoolParser$top-1)).value;
		 RESULT = el.appendElement(e); 
              CUP$CoolParser$result = parser.getSymbolFactory().newSymbol("block_expr_list",6, RESULT);
            }
          return CUP$CoolParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 43: // block_expr_list ::= expr SEMI 
            {
              Expressions RESULT =null;
		Expression e = (Expression)((java_cup.runtime.Symbol) CUP$CoolParser$stack.elementAt(CUP$CoolParser$top-1)).value;
		 RESULT = (new Expressions(curr_lineno())).appendElement(e); 
              CUP$CoolParser$result = parser.getSymbolFactory().newSymbol("block_expr_list",6, RESULT);
            }
          return CUP$CoolParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 42: // branch ::= OBJECTID SEMI TYPEID DARROW expr SEMI 
            {
              branch RESULT =null;
		AbstractSymbol o = (AbstractSymbol)((java_cup.runtime.Symbol) CUP$CoolParser$stack.elementAt(CUP$CoolParser$top-5)).value;
		AbstractSymbol t = (AbstractSymbol)((java_cup.runtime.Symbol) CUP$CoolParser$stack.elementAt(CUP$CoolParser$top-3)).value;
		Expression e = (Expression)((java_cup.runtime.Symbol) CUP$CoolParser$stack.elementAt(CUP$CoolParser$top-1)).value;
		 RESULT = new branch(curr_lineno(), o, t, e); 
              CUP$CoolParser$result = parser.getSymbolFactory().newSymbol("branch",7, RESULT);
            }
          return CUP$CoolParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 41: // branches ::= branches branch 
            {
              Cases RESULT =null;
		Cases el = (Cases)((java_cup.runtime.Symbol) CUP$CoolParser$stack.elementAt(CUP$CoolParser$top-1)).value;
		branch e = (branch)((java_cup.runtime.Symbol) CUP$CoolParser$stack.peek()).value;
		 RESULT = el.appendElement(e); 
              CUP$CoolParser$result = parser.getSymbolFactory().newSymbol("branches",8, RESULT);
            }
          return CUP$CoolParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 40: // branches ::= branch 
            {
              Cases RESULT =null;
		branch e = (branch)((java_cup.runtime.Symbol) CUP$CoolParser$stack.peek()).value;
		 RESULT = (new Cases(curr_lineno())).appendElement(e); 
              CUP$CoolParser$result = parser.getSymbolFactory().newSymbol("branches",8, RESULT);
            }
          return CUP$CoolParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 39: // let ::= OBJECTID COLON TYPEID ASSIGN expr IN expr 
            {
              let RESULT =null;
		AbstractSymbol n = (AbstractSymbol)((java_cup.runtime.Symbol) CUP$CoolParser$stack.elementAt(CUP$CoolParser$top-6)).value;
		AbstractSymbol t = (AbstractSymbol)((java_cup.runtime.Symbol) CUP$CoolParser$stack.elementAt(CUP$CoolParser$top-4)).value;
		Expression i = (Expression)((java_cup.runtime.Symbol) CUP$CoolParser$stack.elementAt(CUP$CoolParser$top-2)).value;
		Expression b = (Expression)((java_cup.runtime.Symbol) CUP$CoolParser$stack.peek()).value;
		 RESULT = new let(curr_lineno(), n, t, i, b); 
              CUP$CoolParser$result = parser.getSymbolFactory().newSymbol("let",11, RESULT);
            }
          return CUP$CoolParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // let ::= OBJECTID COLON TYPEID IN expr 
            {
              let RESULT =null;
		AbstractSymbol n = (AbstractSymbol)((java_cup.runtime.Symbol) CUP$CoolParser$stack.elementAt(CUP$CoolParser$top-4)).value;
		AbstractSymbol t = (AbstractSymbol)((java_cup.runtime.Symbol) CUP$CoolParser$stack.elementAt(CUP$CoolParser$top-2)).value;
		Expression b = (Expression)((java_cup.runtime.Symbol) CUP$CoolParser$stack.peek()).value;
		 RESULT = new let(curr_lineno(), n, t, new no_expr(curr_lineno()), b); 
              CUP$CoolParser$result = parser.getSymbolFactory().newSymbol("let",11, RESULT);
            }
          return CUP$CoolParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // let ::= OBJECTID COLON TYPEID ASSIGN expr COMMA let 
            {
              let RESULT =null;
		AbstractSymbol n = (AbstractSymbol)((java_cup.runtime.Symbol) CUP$CoolParser$stack.elementAt(CUP$CoolParser$top-6)).value;
		AbstractSymbol t = (AbstractSymbol)((java_cup.runtime.Symbol) CUP$CoolParser$stack.elementAt(CUP$CoolParser$top-4)).value;
		Expression i = (Expression)((java_cup.runtime.Symbol) CUP$CoolParser$stack.elementAt(CUP$CoolParser$top-2)).value;
		let l = (let)((java_cup.runtime.Symbol) CUP$CoolParser$stack.peek()).value;
		 RESULT = new let(curr_lineno(), n, t, i, l); 
              CUP$CoolParser$result = parser.getSymbolFactory().newSymbol("let",11, RESULT);
            }
          return CUP$CoolParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // let ::= OBJECTID COLON TYPEID COMMA let 
            {
              let RESULT =null;
		AbstractSymbol n = (AbstractSymbol)((java_cup.runtime.Symbol) CUP$CoolParser$stack.elementAt(CUP$CoolParser$top-4)).value;
		AbstractSymbol t = (AbstractSymbol)((java_cup.runtime.Symbol) CUP$CoolParser$stack.elementAt(CUP$CoolParser$top-2)).value;
		let l = (let)((java_cup.runtime.Symbol) CUP$CoolParser$stack.peek()).value;
		 RESULT = new let(curr_lineno(), n, t, new no_expr(curr_lineno()), l); 
              CUP$CoolParser$result = parser.getSymbolFactory().newSymbol("let",11, RESULT);
            }
          return CUP$CoolParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // expr ::= LET let 
            {
              Expression RESULT =null;
		let l = (let)((java_cup.runtime.Symbol) CUP$CoolParser$stack.peek()).value;
		 RESULT = l; 
              CUP$CoolParser$result = parser.getSymbolFactory().newSymbol("expr",5, RESULT);
            }
          return CUP$CoolParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // expr ::= CASE expr OF branches ESAC 
            {
              Expression RESULT =null;
		Expression e = (Expression)((java_cup.runtime.Symbol) CUP$CoolParser$stack.elementAt(CUP$CoolParser$top-3)).value;
		Cases bs = (Cases)((java_cup.runtime.Symbol) CUP$CoolParser$stack.elementAt(CUP$CoolParser$top-1)).value;
		 RESULT = new typcase(curr_lineno(), e, bs); 
              CUP$CoolParser$result = parser.getSymbolFactory().newSymbol("expr",5, RESULT);
            }
          return CUP$CoolParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // expr ::= LBRACE block_expr_list RBRACE 
            {
              Expression RESULT =null;
		Expressions el = (Expressions)((java_cup.runtime.Symbol) CUP$CoolParser$stack.elementAt(CUP$CoolParser$top-1)).value;
		 RESULT = new block(curr_lineno(), el); 
              CUP$CoolParser$result = parser.getSymbolFactory().newSymbol("expr",5, RESULT);
            }
          return CUP$CoolParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // expr ::= NEW TYPEID 
            {
              Expression RESULT =null;
		AbstractSymbol t = (AbstractSymbol)((java_cup.runtime.Symbol) CUP$CoolParser$stack.peek()).value;
		 RESULT = new new_(curr_lineno(), t); 
              CUP$CoolParser$result = parser.getSymbolFactory().newSymbol("expr",5, RESULT);
            }
          return CUP$CoolParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // expr ::= ISVOID expr 
            {
              Expression RESULT =null;
		Expression e = (Expression)((java_cup.runtime.Symbol) CUP$CoolParser$stack.peek()).value;
		 RESULT = new isvoid(curr_lineno(), e); 
              CUP$CoolParser$result = parser.getSymbolFactory().newSymbol("expr",5, RESULT);
            }
          return CUP$CoolParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // expr ::= expr MULT expr 
            {
              Expression RESULT =null;
		Expression e1 = (Expression)((java_cup.runtime.Symbol) CUP$CoolParser$stack.elementAt(CUP$CoolParser$top-2)).value;
		Expression e2 = (Expression)((java_cup.runtime.Symbol) CUP$CoolParser$stack.peek()).value;
		 RESULT = new mul(curr_lineno(), e1, e2); 
              CUP$CoolParser$result = parser.getSymbolFactory().newSymbol("expr",5, RESULT);
            }
          return CUP$CoolParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // expr ::= expr PLUS expr 
            {
              Expression RESULT =null;
		Expression e1 = (Expression)((java_cup.runtime.Symbol) CUP$CoolParser$stack.elementAt(CUP$CoolParser$top-2)).value;
		Expression e2 = (Expression)((java_cup.runtime.Symbol) CUP$CoolParser$stack.peek()).value;
		 RESULT = new plus(curr_lineno(), e1, e2); 
              CUP$CoolParser$result = parser.getSymbolFactory().newSymbol("expr",5, RESULT);
            }
          return CUP$CoolParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // expr ::= expr MINUS expr 
            {
              Expression RESULT =null;
		Expression e1 = (Expression)((java_cup.runtime.Symbol) CUP$CoolParser$stack.elementAt(CUP$CoolParser$top-2)).value;
		Expression e2 = (Expression)((java_cup.runtime.Symbol) CUP$CoolParser$stack.peek()).value;
		 RESULT = new sub(curr_lineno(), e1, e2); 
              CUP$CoolParser$result = parser.getSymbolFactory().newSymbol("expr",5, RESULT);
            }
          return CUP$CoolParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // expr ::= expr DIV expr 
            {
              Expression RESULT =null;
		Expression e1 = (Expression)((java_cup.runtime.Symbol) CUP$CoolParser$stack.elementAt(CUP$CoolParser$top-2)).value;
		Expression e2 = (Expression)((java_cup.runtime.Symbol) CUP$CoolParser$stack.peek()).value;
		 RESULT = new divide(curr_lineno(), e1, e2); 
              CUP$CoolParser$result = parser.getSymbolFactory().newSymbol("expr",5, RESULT);
            }
          return CUP$CoolParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // expr ::= NEG expr 
            {
              Expression RESULT =null;
		Expression e = (Expression)((java_cup.runtime.Symbol) CUP$CoolParser$stack.peek()).value;
		 RESULT = new comp(curr_lineno(), e); 
              CUP$CoolParser$result = parser.getSymbolFactory().newSymbol("expr",5, RESULT);
            }
          return CUP$CoolParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // expr ::= expr LT expr 
            {
              Expression RESULT =null;
		Expression e1 = (Expression)((java_cup.runtime.Symbol) CUP$CoolParser$stack.elementAt(CUP$CoolParser$top-2)).value;
		Expression e2 = (Expression)((java_cup.runtime.Symbol) CUP$CoolParser$stack.peek()).value;
		 RESULT = new lt(curr_lineno(), e1, e2); 
              CUP$CoolParser$result = parser.getSymbolFactory().newSymbol("expr",5, RESULT);
            }
          return CUP$CoolParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // expr ::= expr LE expr 
            {
              Expression RESULT =null;
		Expression e1 = (Expression)((java_cup.runtime.Symbol) CUP$CoolParser$stack.elementAt(CUP$CoolParser$top-2)).value;
		Expression e2 = (Expression)((java_cup.runtime.Symbol) CUP$CoolParser$stack.peek()).value;
		 RESULT = new leq(curr_lineno(), e1, e2); 
              CUP$CoolParser$result = parser.getSymbolFactory().newSymbol("expr",5, RESULT);
            }
          return CUP$CoolParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // expr ::= expr EQ expr 
            {
              Expression RESULT =null;
		Expression e1 = (Expression)((java_cup.runtime.Symbol) CUP$CoolParser$stack.elementAt(CUP$CoolParser$top-2)).value;
		Expression e2 = (Expression)((java_cup.runtime.Symbol) CUP$CoolParser$stack.peek()).value;
		 RESULT = new eq(curr_lineno(), e1, e2); 
              CUP$CoolParser$result = parser.getSymbolFactory().newSymbol("expr",5, RESULT);
            }
          return CUP$CoolParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // expr ::= NOT expr 
            {
              Expression RESULT =null;
		Expression e = (Expression)((java_cup.runtime.Symbol) CUP$CoolParser$stack.peek()).value;
		 RESULT = new neg(curr_lineno(), e); 
              CUP$CoolParser$result = parser.getSymbolFactory().newSymbol("expr",5, RESULT);
            }
          return CUP$CoolParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // expr ::= LPAREN expr RPAREN 
            {
              Expression RESULT =null;
		Expression e = (Expression)((java_cup.runtime.Symbol) CUP$CoolParser$stack.elementAt(CUP$CoolParser$top-1)).value;
		 RESULT = e; 
              CUP$CoolParser$result = parser.getSymbolFactory().newSymbol("expr",5, RESULT);
            }
          return CUP$CoolParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // expr ::= OBJECTID 
            {
              Expression RESULT =null;
		AbstractSymbol e = (AbstractSymbol)((java_cup.runtime.Symbol) CUP$CoolParser$stack.peek()).value;
		 RESULT = new object(curr_lineno(), e); 
              CUP$CoolParser$result = parser.getSymbolFactory().newSymbol("expr",5, RESULT);
            }
          return CUP$CoolParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // expr ::= INT_CONST 
            {
              Expression RESULT =null;
		AbstractSymbol e = (AbstractSymbol)((java_cup.runtime.Symbol) CUP$CoolParser$stack.peek()).value;
		 RESULT = new int_const(curr_lineno(), e); 
              CUP$CoolParser$result = parser.getSymbolFactory().newSymbol("expr",5, RESULT);
            }
          return CUP$CoolParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // expr ::= STR_CONST 
            {
              Expression RESULT =null;
		AbstractSymbol e = (AbstractSymbol)((java_cup.runtime.Symbol) CUP$CoolParser$stack.peek()).value;
		 RESULT = new string_const(curr_lineno(), e); 
              CUP$CoolParser$result = parser.getSymbolFactory().newSymbol("expr",5, RESULT);
            }
          return CUP$CoolParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // expr ::= BOOL_CONST 
            {
              Expression RESULT =null;
		Boolean e = (Boolean)((java_cup.runtime.Symbol) CUP$CoolParser$stack.peek()).value;
		 RESULT = new bool_const(curr_lineno(), e); 
              CUP$CoolParser$result = parser.getSymbolFactory().newSymbol("expr",5, RESULT);
            }
          return CUP$CoolParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // formal ::= OBJECTID COLON TYPEID 
            {
              formalc RESULT =null;
		AbstractSymbol o = (AbstractSymbol)((java_cup.runtime.Symbol) CUP$CoolParser$stack.elementAt(CUP$CoolParser$top-2)).value;
		AbstractSymbol t = (AbstractSymbol)((java_cup.runtime.Symbol) CUP$CoolParser$stack.peek()).value;
		 RESULT = new formalc(curr_lineno(), o, t); 
              CUP$CoolParser$result = parser.getSymbolFactory().newSymbol("formal",10, RESULT);
            }
          return CUP$CoolParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // formals ::= formals COMMA formal 
            {
              Formals RESULT =null;
		Formals fl = (Formals)((java_cup.runtime.Symbol) CUP$CoolParser$stack.elementAt(CUP$CoolParser$top-2)).value;
		formalc f = (formalc)((java_cup.runtime.Symbol) CUP$CoolParser$stack.peek()).value;
		 RESULT = fl.appendElement(f); 
              CUP$CoolParser$result = parser.getSymbolFactory().newSymbol("formals",9, RESULT);
            }
          return CUP$CoolParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // formals ::= formal 
            {
              Formals RESULT =null;
		formalc f = (formalc)((java_cup.runtime.Symbol) CUP$CoolParser$stack.peek()).value;
		 RESULT = (new Formals(curr_lineno())).appendElement(f); 
              CUP$CoolParser$result = parser.getSymbolFactory().newSymbol("formals",9, RESULT);
            }
          return CUP$CoolParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // formals ::= 
            {
              Formals RESULT =null;
		 RESULT = new Formals(curr_lineno()); 
              CUP$CoolParser$result = parser.getSymbolFactory().newSymbol("formals",9, RESULT);
            }
          return CUP$CoolParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // feature ::= OBJECTID LPAREN formals RPAREN COLON TYPEID LBRACE expr RBRACE SEMI 
            {
              Feature RESULT =null;
		AbstractSymbol o = (AbstractSymbol)((java_cup.runtime.Symbol) CUP$CoolParser$stack.elementAt(CUP$CoolParser$top-9)).value;
		Formals fs = (Formals)((java_cup.runtime.Symbol) CUP$CoolParser$stack.elementAt(CUP$CoolParser$top-7)).value;
		AbstractSymbol t = (AbstractSymbol)((java_cup.runtime.Symbol) CUP$CoolParser$stack.elementAt(CUP$CoolParser$top-4)).value;
		Expression e = (Expression)((java_cup.runtime.Symbol) CUP$CoolParser$stack.elementAt(CUP$CoolParser$top-2)).value;
		 RESULT = new method(curr_lineno(), o, fs, t, e); 
              CUP$CoolParser$result = parser.getSymbolFactory().newSymbol("feature",4, RESULT);
            }
          return CUP$CoolParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // feature ::= OBJECTID COLON TYPEID ASSIGN expr SEMI 
            {
              Feature RESULT =null;
		AbstractSymbol n = (AbstractSymbol)((java_cup.runtime.Symbol) CUP$CoolParser$stack.elementAt(CUP$CoolParser$top-5)).value;
		AbstractSymbol t = (AbstractSymbol)((java_cup.runtime.Symbol) CUP$CoolParser$stack.elementAt(CUP$CoolParser$top-3)).value;
		Expression e = (Expression)((java_cup.runtime.Symbol) CUP$CoolParser$stack.elementAt(CUP$CoolParser$top-1)).value;
		 RESULT = new attr(curr_lineno(), n, t, e); 
              CUP$CoolParser$result = parser.getSymbolFactory().newSymbol("feature",4, RESULT);
            }
          return CUP$CoolParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // feature ::= OBJECTID COLON TYPEID SEMI 
            {
              Feature RESULT =null;
		AbstractSymbol n = (AbstractSymbol)((java_cup.runtime.Symbol) CUP$CoolParser$stack.elementAt(CUP$CoolParser$top-3)).value;
		AbstractSymbol t = (AbstractSymbol)((java_cup.runtime.Symbol) CUP$CoolParser$stack.elementAt(CUP$CoolParser$top-1)).value;
		 RESULT = new attr(curr_lineno(), n, t, new no_expr(curr_lineno())); 
              CUP$CoolParser$result = parser.getSymbolFactory().newSymbol("feature",4, RESULT);
            }
          return CUP$CoolParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // features ::= features feature 
            {
              Features RESULT =null;
		Features fl = (Features)((java_cup.runtime.Symbol) CUP$CoolParser$stack.elementAt(CUP$CoolParser$top-1)).value;
		Feature f = (Feature)((java_cup.runtime.Symbol) CUP$CoolParser$stack.peek()).value;
		 RESULT = fl.appendElement(f); 
              CUP$CoolParser$result = parser.getSymbolFactory().newSymbol("features",3, RESULT);
            }
          return CUP$CoolParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // features ::= feature 
            {
              Features RESULT =null;
		Feature f = (Feature)((java_cup.runtime.Symbol) CUP$CoolParser$stack.peek()).value;
		 RESULT = (new Features(curr_lineno())).appendElement(f); 
              CUP$CoolParser$result = parser.getSymbolFactory().newSymbol("features",3, RESULT);
            }
          return CUP$CoolParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // features ::= 
            {
              Features RESULT =null;
		 RESULT = new Features(curr_lineno()); 
              CUP$CoolParser$result = parser.getSymbolFactory().newSymbol("features",3, RESULT);
            }
          return CUP$CoolParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // class ::= CLASS error SEMI 
            {
              class_c RESULT =null;

              CUP$CoolParser$result = parser.getSymbolFactory().newSymbol("class",2, RESULT);
            }
          return CUP$CoolParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // class ::= CLASS TYPEID INHERITS TYPEID LBRACE features RBRACE SEMI 
            {
              class_c RESULT =null;
		AbstractSymbol n = (AbstractSymbol)((java_cup.runtime.Symbol) CUP$CoolParser$stack.elementAt(CUP$CoolParser$top-6)).value;
		AbstractSymbol p = (AbstractSymbol)((java_cup.runtime.Symbol) CUP$CoolParser$stack.elementAt(CUP$CoolParser$top-4)).value;
		Features f = (Features)((java_cup.runtime.Symbol) CUP$CoolParser$stack.elementAt(CUP$CoolParser$top-2)).value;
		 RESULT = new class_c(curr_lineno(), n, p, f, curr_filename()); 
              CUP$CoolParser$result = parser.getSymbolFactory().newSymbol("class",2, RESULT);
            }
          return CUP$CoolParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // class ::= CLASS TYPEID LBRACE features RBRACE SEMI 
            {
              class_c RESULT =null;
		AbstractSymbol n = (AbstractSymbol)((java_cup.runtime.Symbol) CUP$CoolParser$stack.elementAt(CUP$CoolParser$top-4)).value;
		Features f = (Features)((java_cup.runtime.Symbol) CUP$CoolParser$stack.elementAt(CUP$CoolParser$top-2)).value;
		 RESULT = new class_c(curr_lineno(), n,
		                   AbstractTable.idtable.addString("Object"),
				   f, curr_filename()); 
              CUP$CoolParser$result = parser.getSymbolFactory().newSymbol("class",2, RESULT);
            }
          return CUP$CoolParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // class_list ::= class_list class 
            {
              Classes RESULT =null;
		Classes cl = (Classes)((java_cup.runtime.Symbol) CUP$CoolParser$stack.elementAt(CUP$CoolParser$top-1)).value;
		class_c c = (class_c)((java_cup.runtime.Symbol) CUP$CoolParser$stack.peek()).value;
		 RESULT = cl.appendElement(c); 
              CUP$CoolParser$result = parser.getSymbolFactory().newSymbol("class_list",1, RESULT);
            }
          return CUP$CoolParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // class_list ::= class 
            {
              Classes RESULT =null;
		class_c c = (class_c)((java_cup.runtime.Symbol) CUP$CoolParser$stack.peek()).value;
		 RESULT = (new Classes(curr_lineno())).appendElement(c); 
              CUP$CoolParser$result = parser.getSymbolFactory().newSymbol("class_list",1, RESULT);
            }
          return CUP$CoolParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // $START ::= program EOF 
            {
              Object RESULT =null;
		programc start_val = (programc)((java_cup.runtime.Symbol) CUP$CoolParser$stack.elementAt(CUP$CoolParser$top-1)).value;
		RESULT = start_val;
              CUP$CoolParser$result = parser.getSymbolFactory().newSymbol("$START",0, RESULT);
            }
          /* ACCEPT */
          CUP$CoolParser$parser.done_parsing();
          return CUP$CoolParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // program ::= class_list 
            {
              programc RESULT =null;
		Classes cl = (Classes)((java_cup.runtime.Symbol) CUP$CoolParser$stack.peek()).value;
		 RESULT = new programc(curr_lineno(), cl); 
              CUP$CoolParser$result = parser.getSymbolFactory().newSymbol("program",0, RESULT);
            }
          return CUP$CoolParser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number found in internal parse table");

        }
    }
}

