#!/bin/csh -f
# uncomment to use all the reference implementations
# ../../bin/lexer $* | ../../bin/parser
# uncomment to use reference implementations with my parser
# ../../bin/lexer  $* | ./parser $*

# uncomment to only use my implementations
../PA2J/lexer $* | ./parser $*
